// JAIWA Resource Discovery Platform - Centralized Data
const CATEGORIES = [
  {
    name: 'Learning Resources',
    icon: '📚',
    description: 'Educational content and learning platforms',
    subcategories: ['Learning English', 'Web Development', 'AI Learning', 'Digital Marketing', 'Business']
  },
  {
    name: 'AI Tools',
    icon: '🤖',
    description: 'AI-powered tools for productivity and creation',
    subcategories: ['Students', 'Web Developers', 'Content Creators', 'Business Owners', 'Digital Marketers', 'Researchers & Knowledge']
  },
  {
    name: 'Online Success Toolkit',
    icon: '🚀',
    description: 'Tools for freelancing, portfolios, and online growth',
    subcategories: ['Learn & Upskill', 'Portfolio & Personal Branding', 'Freelancing & Remote Work', 'Startup & Business Resources', 'Productivity & Research']
  },
  {
    name: 'Web Developer Toolkit',
    icon: '💻',
    description: 'Professional tools for web development',
    subcategories: ['AI-Powered Development', 'Backend & Database Tools', 'API & Testing Tools', 'Hosting & Deployment', 'Developer Utilities', 'Version Control & Collaboration']
  }
];

// JAIWA Resource Discovery Platform - Centralized Data
const RESOURCES = [
  // LEARNING RESOURCES
  {
    id: 'bbc-english',
    title: 'BBC Learning English',
    category: 'Learning Resources',
    subcategory: 'Learning English',
    description: 'Learning grammar, vocabulary, pronunciation, speaking and listening skills through free lessons, videos and quizzes.',
    url: 'https://www.bbc.co.uk/learningenglish',
    featured: true,
    dateAdded: '2024-01-15',
    tags: ['english', 'grammar', 'vocabulary', 'speaking', 'listening']
  },
  {
    id: 'voa-english',
    title: 'VOA Learning English',
    category: 'Learning Resources',
    subcategory: 'Learning English',
    description: 'Improve listening, reading and speaking skills with slow-speed English news and daily lessons.',
    url: 'https://learningenglish.voanews.com',
    featured: false,
    dateAdded: '2024-01-15',
    tags: ['english', 'listening', 'news', 'speaking']
  },
  {
    id: 'oxford-english',
    title: 'Oxford Online English',
    category: 'Learning Resources',
    subcategory: 'Learning English',
    description: 'Free English lessons from beginner to advanced, including grammar, speaking, writing and IELTS preparation.',
    url: 'https://www.oxfordonlineenglish.com',
    featured: true,
    dateAdded: '2024-01-15',
    tags: ['english', 'grammar', 'ielts', 'writing']
  },
  {
    id: 'british-council',
    title: 'British Council Learn English',
    category: 'Learning Resources',
    subcategory: 'Learning English',
    description: 'Free resources for grammar, vocabulary, reading, listening and exam preparation.',
    url: 'https://learningenglish.britishcouncil.org',
    featured: false,
    dateAdded: '2024-01-15',
    tags: ['english', 'reading', 'exam', 'vocabulary']
  },
  {
    id: 'myanmar-boc',
    title: 'Myanmar BOC',
    category: 'Learning Resources',
    subcategory: 'Learning English',
    description: 'Myanmar-based English Learning community sharing lessons, tips and study materials.',
    url: 'https://myanmarboc.com',
    featured: false,
    dateAdded: '2024-01-15',
    tags: ['english', 'community', 'myanmar']
  },
  {
    id: 'talk-english',
    title: 'Talk English',
    category: 'Learning Resources',
    subcategory: 'Learning English',
    description: 'Practice daily conversations, speaking patterns and real-life English communication skills.',
    url: 'https://www.talkenglish.com',
    featured: false,
    dateAdded: '2024-01-15',
    tags: ['english', 'conversation', 'speaking']
  },
  {
    id: 'freecodecamp',
    title: 'freeCodeCamp',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'Free interactive coding lessons and projects for beginners to advanced developers.',
    url: 'https://www.freecodecamp.org/',
    featured: true,
    dateAdded: '2024-01-14',
    tags: ['coding', 'web-dev', 'javascript', 'python']
  },
  {
    id: 'odin-project',
    title: 'The Odin Project',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'A complete roadmap to becoming a full-stack web developer.',
    url: 'https://theodinproject.com',
    featured: true,
    dateAdded: '2024-01-14',
    tags: ['web-dev', 'fullstack', 'curriculum']
  },
  {
    id: 'w3schools',
    title: 'W3Schools',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'Easy tutorials and references for HTML, CSS, JavaScript and more.',
    url: 'https://www.w3schools.com',
    featured: false,
    dateAdded: '2024-01-14',
    tags: ['html', 'css', 'javascript', 'reference']
  },
  {
    id: 'mdn',
    title: 'MDN Web Docs',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'Professional documentation used by web developers worldwide.',
    url: 'https://developer.mozilla.org',
    featured: false,
    dateAdded: '2024-01-14',
    tags: ['web-dev', 'documentation', 'reference']
  },
  {
    id: 'roadmapsh',
    title: 'Roadmap.sh',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'Visual learning paths for frontend, backend and full-stack development.',
    url: 'https://roadmap.sh',
    featured: true,
    dateAdded: '2024-01-14',
    tags: ['learning-path', 'web-dev', 'curriculum']
  },
  {
    id: 'cs50',
    title: 'CS50 Harvard',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'One of the world\'s most popular introduction to computer science courses.',
    url: 'https://cs50.harvard.edu',
    featured: false,
    dateAdded: '2024-01-14',
    tags: ['computer-science', 'harvard', 'free-course']
  },
  {
    id: 'scrimba',
    title: 'Scrimba',
    category: 'Learning Resources',
    subcategory: 'Web Development',
    description: 'Interactive coding courses where you learn by doing.',
    url: 'https://www.scrimba.com',
    featured: false,
    dateAdded: '2024-01-14',
    tags: ['interactive', 'coding', 'courses']
  },
  {
    id: 'google-ai',
    title: 'Google AI Essentials',
    category: 'Learning Resources',
    subcategory: 'AI Learning',
    description: 'Practical AI skills for productivity and workplace tasks.',
    url: 'https://www.coursera.org/professional-certificates/google-ai-essentials',
    featured: true,
    dateAdded: '2024-01-13',
    tags: ['ai', 'google', 'certification']
  },
  {
    id: 'elements-ai',
    title: 'Elements of AI',
    category: 'Learning Resources',
    subcategory: 'AI Learning',
    description: 'Beginner-friendly introduction to artificial intelligence.',
    url: 'https://www.elementsofai.com',
    featured: false,
    dateAdded: '2024-01-13',
    tags: ['ai', 'beginners', 'free']
  },
  {
    id: 'deeplearning-ai',
    title: 'DeepLearning.AI',
    category: 'Learning Resources',
    subcategory: 'AI Learning',
    description: 'Professional courses on AI, machine learning and generative AI.',
    url: 'https://www.deeplearning.ai',
    featured: false,
    dateAdded: '2024-01-13',
    tags: ['ai', 'machine-learning', 'courses']
  },
  {
    id: 'microsoft-ai',
    title: 'Microsoft AI Learn',
    category: 'Learning Resources',
    subcategory: 'AI Learning',
    description: 'Learn AI fundamentals and Azure AI technologies.',
    url: 'https://learn.microsoft.com/training/paths/get-started-with-artificial-intelligence-on-azure',
    featured: false,
    dateAdded: '2024-01-13',
    tags: ['ai', 'azure', 'microsoft']
  },
  {
    id: 'huggingface',
    title: 'Hugging Face Learn',
    category: 'Learning Resources',
    subcategory: 'AI Learning',
    description: 'Explore open-source AI models, NLP and generative AI.',
    url: 'https://huggingface.co/learn',
    featured: false,
    dateAdded: '2024-01-13',
    tags: ['ai', 'nlp', 'open-source']
  },
  {
    id: 'fcc-ai',
    title: 'freeCodeCamp AI Courses',
    category: 'Learning Resources',
    subcategory: 'AI Learning',
    description: 'Free AI, machine learning and Python tutorials for beginners.',
    url: 'https://www.freecodecamp.org/learn/machine-learning-with-python/',
    featured: false,
    dateAdded: '2024-01-13',
    tags: ['ai', 'python', 'free']
  },
  {
    id: 'google-digital',
    title: 'Google Digital Garage',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Free digital marketing fundamentals, SEO, social media, email marketing certification from Google.',
    url: 'https://learndigital.withgoogle.com/digitalgarage',
    featured: true,
    dateAdded: '2024-01-12',
    tags: ['digital-marketing', 'seo', 'google', 'free']
  },
  {
    id: 'hubspot-academy',
    title: 'HubSpot Academy',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Inbound marketing, content marketing, SEO, social media strategy courses.',
    url: 'https://academy.hubspot.com/',
    featured: false,
    dateAdded: '2024-01-12',
    tags: ['marketing', 'seo', 'inbound']
  },
  {
    id: 'moz-seo',
    title: 'Moz Beginner\'s Guide to SEO',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Complete beginner guide to Search Engine Optimization.',
    url: 'https://moz.com/beginners-guide-to-seo',
    featured: false,
    dateAdded: '2024-01-12',
    tags: ['seo', 'marketing', 'guide']
  },
  {
    id: 'hootsuite',
    title: 'Hootsuite Academy',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Learn social media marketing and platform management skills.',
    url: 'https://education.hootsuite.com/',
    featured: false,
    dateAdded: '2024-01-12',
    tags: ['social-media', 'marketing']
  },
  {
    id: 'google-analytics',
    title: 'Google Analytics Academy',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Learn website analysis, user behavior tracking and data-driven marketing.',
    url: 'http://analytics.google.com/analytics/academy/',
    featured: false,
    dateAdded: '2024-01-12',
    tags: ['analytics', 'google', 'data']
  },
  {
    id: 'semrush-academy',
    title: 'Semrush Academy',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Free courses on SEO, content marketing, keyword research and digital marketing strategies.',
    url: 'https://www.semrush.com/academy/',
    featured: false,
    dateAdded: '2024-01-12',
    tags: ['seo', 'marketing', 'tools']
  },
  {
    id: 'ahrefs-academy',
    title: 'Ahrefs Blog & Academy',
    category: 'Learning Resources',
    subcategory: 'Digital Marketing',
    description: 'Practical SEO training, keyword research, backlink analysis and content optimization.',
    url: 'https://ahrefs.com/academy',
    featured: false,
    dateAdded: '2024-01-12',
    tags: ['seo', 'backlinks', 'keyword-research']
  },
  {
    id: 'mobi',
    title: 'My Own Business Institute',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Free entrepreneurship courses covering business planning, marketing and operations.',
    url: 'https://www.myownbusiness.org',
    featured: false,
    dateAdded: '2024-01-11',
    tags: ['business', 'entrepreneurship', 'free']
  },
  {
    id: 'sba',
    title: 'SBA Learning Platform',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Small business training resources, startup guides and business management lessons.',
    url: 'https://learning.sba.gov',
    featured: false,
    dateAdded: '2024-01-11',
    tags: ['business', 'startup', 'small-business']
  },
  {
    id: 'coursera-business',
    title: 'Coursera Business Courses',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Business, finance, leadership and entrepreneurship courses from top universities.',
    url: 'https://www.coursera.org/browse/business',
    featured: false,
    dateAdded: '2024-01-11',
    tags: ['business', 'finance', 'courses']
  },
  {
    id: 'alison-business',
    title: 'Alison Business Courses',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Free online business courses with certificates in management, marketing and finance.',
    url: 'https://alison.com/tag/business',
    featured: false,
    dateAdded: '2024-01-11',
    tags: ['business', 'free', 'certificates']
  },
  {
    id: 'khan-finance',
    title: 'Khan Academy Finance & Economics',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Learn economics, finance and personal money management fundamentals.',
    url: 'https://www.khanacademy.org/economics-finance-domain',
    featured: false,
    dateAdded: '2024-01-11',
    tags: ['finance', 'economics', 'free']
  },
  {
    id: 'hbr',
    title: 'Harvard Business Review',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Insights on leadership, strategy, management and business trends.',
    url: 'https://hbr.org',
    featured: true,
    dateAdded: '2024-01-11',
    tags: ['business', 'leadership', 'strategy']
  },
  {
    id: 'yc-library',
    title: 'Y Combinator Startup Library',
    category: 'Learning Resources',
    subcategory: 'Business',
    description: 'Practical startup lessons from one of the world\'s startup accelerators.',
    url: 'https://www.ycombinator.com/library',
    featured: false,
    dateAdded: '2024-01-11',
    tags: ['startup', 'entrepreneurship', 'free']
  },
  
  // AI TOOLS
  {
    id: 'chatgpt',
    title: 'ChatGPT',
    category: 'AI Tools',
    subcategory: 'Students',
    description: 'AI assistant for studying, writing, research and problem-solving.',
    url: 'https://chatgpt.com',
    featured: true,
    dateAdded: '2024-01-10',
    tags: ['ai', 'assistant', 'writing', 'students']
  },
  {
    id: 'gemini',
    title: 'Google Gemini',
    category: 'AI Tools',
    subcategory: 'Students',
    description: 'AI assistant for learning, research and productivity.',
    url: 'https://gemini.google.com',
    featured: false,
    dateAdded: '2024-01-10',
    tags: ['ai', 'google', 'assistant']
  },
  {
    id: 'notebooklm',
    title: 'NotebookLM',
    category: 'AI Tools',
    subcategory: 'Students',
    description: 'AI-powered research and note-taking tool by Google.',
    url: 'https://notebooklm.google.com',
    featured: false,
    dateAdded: '2024-01-10',
    tags: ['note-taking', 'research', 'google']
  },
  {
    id: 'grammarly',
    title: 'Grammarly',
    category: 'AI Tools',
    subcategory: 'Students',
    description: 'Writing assistant for grammar, spelling and communication.',
    url: 'https://www.grammarly.com',
    featured: false,
    dateAdded: '2024-01-10',
    tags: ['writing', 'grammar', 'ai']
  },
  {
    id: 'khanmigo',
    title: 'Khanmigo',
    category: 'AI Tools',
    subcategory: 'Students',
    description: 'AI tutor designed for students and learners.',
    url: 'https://www.khanacademy.org/khan-labs',
    featured: false,
    dateAdded: '2024-01-10',
    tags: ['tutoring', 'ai', 'students']
  },
  {
    id: 'deepl',
    title: 'DeepL',
    category: 'AI Tools',
    subcategory: 'Students',
    description: 'Translation tool for accurate language learning and writing support.',
    url: 'https://www.deepl.com',
    featured: false,
    dateAdded: '2024-01-10',
    tags: ['translation', 'language', 'writing']
  },
  {
    id: 'claude',
    title: 'Claude',
    category: 'AI Tools',
    subcategory: 'Web Developers',
    description: 'Useful for reading long code, analyzing projects, and explaining complex development problems.',
    url: 'https://claude.ai',
    featured: true,
    dateAdded: '2024-01-09',
    tags: ['ai', 'coding', 'development']
  },
  {
    id: 'lovable',
    title: 'Lovable',
    category: 'AI Tools',
    subcategory: 'Web Developers',
    description: 'Build websites and web applications using AI-powered development tools.',
    url: 'https://lovable.dev',
    featured: false,
    dateAdded: '2024-01-09',
    tags: ['web-dev', 'ai', 'builder']
  },
  {
    id: 'copilot',
    title: 'GitHub Copilot',
    category: 'AI Tools',
    subcategory: 'Web Developers',
    description: 'AI coding assistant that suggests code directly inside your editor.',
    url: 'https://github.com/features/copilot',
    featured: false,
    dateAdded: '2024-01-09',
    tags: ['coding', 'ai', 'github']
  },
  {
    id: 'v0',
    title: 'v0 by Vercel',
    category: 'AI Tools',
    subcategory: 'Web Developers',
    description: 'Generate modern UI components and frontend layouts using AI.',
    url: 'https://v0.dev',
    featured: false,
    dateAdded: '2024-01-09',
    tags: ['ui', 'components', 'ai', 'web-dev']
  },
  {
    id: 'bolt',
    title: 'Bolt.new',
    category: 'AI Tools',
    subcategory: 'Web Developers',
    description: 'Build full-stack web apps quickly using AI-powered development.',
    url: 'https://bolt.new',
    featured: true,
    dateAdded: '2024-01-09',
    tags: ['web-dev', 'ai', 'fullstack']
  },
  {
    id: 'cursor',
    title: 'Cursor',
    category: 'AI Tools',
    subcategory: 'Web Developers',
    description: 'AI code editor designed for faster coding, debugging, and project building.',
    url: 'https://cursor.com',
    featured: false,
    dateAdded: '2024-01-09',
    tags: ['code-editor', 'ai', 'development']
  },
  {
    id: 'canva-ai',
    title: 'Canva AI',
    category: 'AI Tools',
    subcategory: 'Content Creators',
    description: 'Design posters, social media graphics, presentations with AI features.',
    url: 'https://www.canva.com/ai',
    featured: true,
    dateAdded: '2024-01-08',
    tags: ['design', 'graphics', 'ai']
  },
  {
    id: 'capcut',
    title: 'CapCut AI',
    category: 'AI Tools',
    subcategory: 'Content Creators',
    description: 'Create and edit videos faster with captions, templates, effects, and AI editing.',
    url: 'https://www.capcut.com',
    featured: false,
    dateAdded: '2024-01-08',
    tags: ['video-editing', 'ai', 'content-creation']
  },
  {
    id: 'elevenlabs',
    title: 'ElevenLabs',
    category: 'AI Tools',
    subcategory: 'Content Creators',
    description: 'Generate realistic AI voices for videos, ads, storytelling, and narration.',
    url: 'https://elevenlabs.io',
    featured: false,
    dateAdded: '2024-01-08',
    tags: ['voice', 'audio', 'ai', 'content']
  },
  {
    id: 'gamma',
    title: 'Gamma',
    category: 'AI Tools',
    subcategory: 'Content Creators',
    description: 'Create presentations, documents, and visual content using AI.',
    url: 'https://gamma.app',
    featured: false,
    dateAdded: '2024-01-08',
    tags: ['presentation', 'documents', 'ai']
  },
  {
    id: 'midjourney',
    title: 'Midjourney',
    category: 'AI Tools',
    subcategory: 'Content Creators',
    description: 'Generate high-quality AI images and creative visuals from text prompts.',
    url: 'https://www.midjourney.com',
    featured: false,
    dateAdded: '2024-01-08',
    tags: ['image-generation', 'ai', 'art']
  },
  {
    id: 'hubspot-ai',
    title: 'HubSpot AI',
    category: 'AI Tools',
    subcategory: 'Business Owners',
    description: 'AI tools for marketing, sales, customer service, and business growth.',
    url: 'https://www.hubspot.com/artificial-intelligence',
    featured: false,
    dateAdded: '2024-01-07',
    tags: ['business', 'marketing', 'crm', 'ai']
  },
  {
    id: '10x',
    title: '10x',
    category: 'AI Tools',
    subcategory: 'Business Owners',
    description: 'AI-powered productivity platform designed to automate workflows.',
    url: 'https://10x.ai',
    featured: false,
    dateAdded: '2024-01-07',
    tags: ['productivity', 'automation', 'ai']
  },
  {
    id: 'notion-ai',
    title: 'Notion AI',
    category: 'AI Tools',
    subcategory: 'Business Owners',
    description: 'Organize notes, plans, tasks, documents, and business ideas in one workspace.',
    url: 'https://www.notion.so/product/ai',
    featured: false,
    dateAdded: '2024-01-07',
    tags: ['note-taking', 'productivity', 'ai']
  },
  {
    id: 'semrush-ai',
    title: 'Semrush AI',
    category: 'AI Tools',
    subcategory: 'Digital Marketers',
    description: 'SEO and marketing platform with AI tools for keyword research and content analysis.',
    url: 'https://www.semrush.com',
    featured: false,
    dateAdded: '2024-01-06',
    tags: ['seo', 'marketing', 'ai']
  },
  {
    id: 'ahrefs-ai',
    title: 'Ahrefs AI',
    category: 'AI Tools',
    subcategory: 'Digital Marketers',
    description: 'AI-powered SEO tools for content ideas, keyword research, and website growth.',
    url: 'https://ahrefs.com',
    featured: false,
    dateAdded: '2024-01-06',
    tags: ['seo', 'tools', 'ai']
  },
  {
    id: 'perplexity',
    title: 'Perplexity',
    category: 'AI Tools',
    subcategory: 'Researchers & Knowledge',
    description: 'AI-powered search engine that provides accurate answers with cited sources.',
    url: 'https://www.perplexity.ai',
    featured: true,
    dateAdded: '2024-01-05',
    tags: ['search', 'research', 'ai']
  },
  {
    id: 'manus',
    title: 'Manus',
    category: 'AI Tools',
    subcategory: 'Researchers & Knowledge',
    description: 'Autonomous AI agent designed to research, analyze and complete complex tasks.',
    url: 'https://manus.im',
    featured: false,
    dateAdded: '2024-01-05',
    tags: ['ai', 'agent', 'research']
  },
  {
    id: 'grok',
    title: 'Grok',
    category: 'AI Tools',
    subcategory: 'Researchers & Knowledge',
    description: 'Real-time AI assistant with access to live information and trending topics.',
    url: 'https://grok.com',
    featured: false,
    dateAdded: '2024-01-05',
    tags: ['ai', 'real-time', 'search']
  },
  {
    id: 'consensus',
    title: 'Consensus',
    category: 'AI Tools',
    subcategory: 'Researchers & Knowledge',
    description: 'AI search engine focused on scientific research and academic papers.',
    url: 'https://consensus.app',
    featured: false,
    dateAdded: '2024-01-05',
    tags: ['research', 'academic', 'ai']
  },

  // ONLINE SUCCESS TOOLKIT
  {
    id: 'fcc-upskill',
    title: 'freeCodeCamp',
    category: 'Online Success Toolkit',
    subcategory: 'Learn & Upskill',
    description: 'Learn web development, JavaScript, APIs, databases, and earn free certificates.',
    url: 'https://freecodecamp.org',
    featured: true,
    dateAdded: '2024-01-04',
    tags: ['learning', 'coding', 'free', 'certification']
  },
  {
    id: 'roadmapsh-toolkit',
    title: 'Roadmap.sh',
    category: 'Online Success Toolkit',
    subcategory: 'Learn & Upskill',
    description: 'Explore clear learning paths for frontend, backend, DevOps, cybersecurity.',
    url: 'https://roadmap.sh',
    featured: false,
    dateAdded: '2024-01-04',
    tags: ['learning', 'roadmap', 'tech-careers']
  },
  {
    id: 'google-skillshop',
    title: 'Google Skillshop',
    category: 'Online Success Toolkit',
    subcategory: 'Learn & Upskill',
    description: 'Free certifications for Google Ads, Analytics, YouTube, and digital skills.',
    url: 'https://skillshop.withgoogle.com',
    featured: false,
    dateAdded: '2024-01-04',
    tags: ['google', 'certification', 'marketing']
  },
  {
    id: 'cs50-upskill',
    title: 'CS50',
    category: 'Online Success Toolkit',
    subcategory: 'Learn & Upskill',
    description: 'One of the world\'s most respected free computer science courses from Harvard.',
    url: 'https://cs50.harvard.edu',
    featured: false,
    dateAdded: '2024-01-04',
    tags: ['computer-science', 'harvard', 'free']
  },
  {
    id: 'github-portfolio',
    title: 'GitHub',
    category: 'Online Success Toolkit',
    subcategory: 'Portfolio & Personal Branding',
    description: 'Showcase your projects, collaborate with developers, and build a portfolio.',
    url: 'https://github.com',
    featured: true,
    dateAdded: '2024-01-03',
    tags: ['portfolio', 'coding', 'collaboration']
  },
  {
    id: 'behance',
    title: 'Behance',
    category: 'Online Success Toolkit',
    subcategory: 'Portfolio & Personal Branding',
    description: 'Display creative work and attract potential clients or employers.',
    url: 'https://behance.net',
    featured: false,
    dateAdded: '2024-01-03',
    tags: ['portfolio', 'design', 'creative']
  },
  {
    id: 'dribbble',
    title: 'Dribbble',
    category: 'Online Success Toolkit',
    subcategory: 'Portfolio & Personal Branding',
    description: 'Share design projects and connect with professional designers worldwide.',
    url: 'https://dribbble.com',
    featured: false,
    dateAdded: '2024-01-03',
    tags: ['portfolio', 'design', 'community']
  },
  {
    id: 'linkedin',
    title: 'LinkedIn',
    category: 'Online Success Toolkit',
    subcategory: 'Portfolio & Personal Branding',
    description: 'Build your professional network, personal brand, and discover opportunities.',
    url: 'https://linkedin.com',
    featured: true,
    dateAdded: '2024-01-03',
    tags: ['networking', 'professional', 'branding']
  },
  {
    id: 'medium',
    title: 'Medium',
    category: 'Online Success Toolkit',
    subcategory: 'Portfolio & Personal Branding',
    description: 'Publish articles, tutorials, and share your expertise with a global audience.',
    url: 'https://medium.com',
    featured: false,
    dateAdded: '2024-01-03',
    tags: ['blogging', 'writing', 'content']
  },
  {
    id: 'upwork',
    title: 'Upwork',
    category: 'Online Success Toolkit',
    subcategory: 'Freelancing & Remote Work',
    description: 'One of the largest freelance marketplaces for developers, marketers, designers.',
    url: 'https://upwork.com',
    featured: true,
    dateAdded: '2024-01-02',
    tags: ['freelancing', 'marketplace', 'jobs']
  },
  {
    id: 'fiverr',
    title: 'Fiverr',
    category: 'Online Success Toolkit',
    subcategory: 'Freelancing & Remote Work',
    description: 'Offer services and digital products to clients around the world.',
    url: 'https://fiverr.com',
    featured: false,
    dateAdded: '2024-01-02',
    tags: ['freelancing', 'services', 'marketplace']
  },
  {
    id: 'freelancer',
    title: 'Freelancer',
    category: 'Online Success Toolkit',
    subcategory: 'Freelancing & Remote Work',
    description: 'Find projects in programming, design, writing, marketing, and more.',
    url: 'https://freelancer.com',
    featured: false,
    dateAdded: '2024-01-02',
    tags: ['freelancing', 'projects', 'marketplace']
  },
  {
    id: 'contra',
    title: 'Contra',
    category: 'Online Success Toolkit',
    subcategory: 'Freelancing & Remote Work',
    description: 'Commission-free freelancing platform focused on creators and professionals.',
    url: 'https://contra.com',
    featured: false,
    dateAdded: '2024-01-02',
    tags: ['freelancing', 'commission-free', 'creators']
  },
  {
    id: 'we-work-remotely',
    title: 'We Work Remotely',
    category: 'Online Success Toolkit',
    subcategory: 'Freelancing & Remote Work',
    description: 'Discover remote jobs from startups and companies worldwide.',
    url: 'https://weworkremotely.com',
    featured: false,
    dateAdded: '2024-01-02',
    tags: ['remote-jobs', 'jobs', 'freelancing']
  },
  {
    id: 'indie-hackers',
    title: 'Indie Hackers',
    category: 'Online Success Toolkit',
    subcategory: 'Startup & Business Resources',
    description: 'Learn how independent founders build online businesses and generate revenue.',
    url: 'https://indiehackers.com',
    featured: true,
    dateAdded: '2024-01-01',
    tags: ['startup', 'entrepreneurship', 'community']
  },
  {
    id: 'product-hunt',
    title: 'Product Hunt',
    category: 'Online Success Toolkit',
    subcategory: 'Startup & Business Resources',
    description: 'Discover trending apps, tools, startups, and new business ideas.',
    url: 'https://producthunt.com',
    featured: false,
    dateAdded: '2024-01-01',
    tags: ['products', 'startups', 'discovery']
  },
  {
    id: 'starter-story',
    title: 'Starter Story',
    category: 'Online Success Toolkit',
    subcategory: 'Startup & Business Resources',
    description: 'Read real business case studies from entrepreneurs and online business owners.',
    url: 'https://starterstory.com',
    featured: false,
    dateAdded: '2024-01-01',
    tags: ['case-studies', 'business', 'entrepreneurship']
  },
  {
    id: 'exploding-topics',
    title: 'Exploding Topics',
    category: 'Online Success Toolkit',
    subcategory: 'Startup & Business Resources',
    description: 'Identify emerging trends before they become mainstream opportunities.',
    url: 'https://explodingtopics.com',
    featured: false,
    dateAdded: '2024-01-01',
    tags: ['trends', 'market-research', 'opportunities']
  },
  {
    id: 'perplexity-toolkit',
    title: 'Perplexity',
    category: 'Online Success Toolkit',
    subcategory: 'Productivity & Research',
    description: 'Research faster using AI-powered search with cited sources.',
    url: 'https://perplexity.ai',
    featured: false,
    dateAdded: '2023-12-31',
    tags: ['research', 'ai', 'productivity']
  },
  {
    id: 'notion-toolkit',
    title: 'Notion',
    category: 'Online Success Toolkit',
    subcategory: 'Productivity & Research',
    description: 'Manage goals, projects, notes, and learning systems in one place.',
    url: 'https://notion.so',
    featured: false,
    dateAdded: '2023-12-31',
    tags: ['productivity', 'note-taking', 'workspace']
  },
  {
    id: 'notebooklm-toolkit',
    title: 'NotebookLM',
    category: 'Online Success Toolkit',
    subcategory: 'Productivity & Research',
    description: 'Turn documents, notes, and research materials into knowledge assistant.',
    url: 'https://notebooklm.google.com',
    featured: false,
    dateAdded: '2023-12-31',
    tags: ['research', 'ai', 'note-taking']
  },
  {
    id: 'raindrop',
    title: 'Raindrop.io',
    category: 'Online Success Toolkit',
    subcategory: 'Productivity & Research',
    description: 'Organize and manage useful websites, resources, and bookmarks.',
    url: 'https://raindrop.io',
    featured: false,
    dateAdded: '2023-12-31',
    tags: ['bookmarks', 'organization', 'productivity']
  },
  {
    id: 'readwise',
    title: 'Readwise',
    category: 'Online Success Toolkit',
    subcategory: 'Productivity & Research',
    description: 'Save, review, and remember important ideas from articles and books.',
    url: 'https://readwise.io',
    featured: false,
    dateAdded: '2023-12-31',
    tags: ['reading', 'retention', 'learning']
  },

  // WEB DEVELOPER TOOLKIT
  {
    id: 'cursor-dev',
    title: 'Cursor',
    category: 'Web Developer Toolkit',
    subcategory: 'AI-Powered Development',
    description: 'AI-first code editor with deep project understanding and code generation.',
    url: 'https://cursor.com',
    featured: true,
    dateAdded: '2023-12-30',
    tags: ['code-editor', 'ai', 'development']
  },
  {
    id: 'copilot-dev',
    title: 'GitHub Copilot',
    category: 'Web Developer Toolkit',
    subcategory: 'AI-Powered Development',
    description: 'Your AI pair programmer that helps write, explain, and refactor code.',
    url: 'https://github.com/features/copilot',
    featured: false,
    dateAdded: '2023-12-30',
    tags: ['ai', 'coding', 'development']
  },
  {
    id: 'windsurf',
    title: 'Windsurf',
    category: 'Web Developer Toolkit',
    subcategory: 'AI-Powered Development',
    description: 'Modern AI development environment with project-wide context awareness.',
    url: 'https://windsurf.com',
    featured: false,
    dateAdded: '2023-12-30',
    tags: ['ide', 'ai', 'development']
  },
  {
    id: 'bolt-dev',
    title: 'Bolt.new',
    category: 'Web Developer Toolkit',
    subcategory: 'AI-Powered Development',
    description: 'Build and deploy full-stack applications using natural language prompts.',
    url: 'https://bolt.new',
    featured: true,
    dateAdded: '2023-12-30',
    tags: ['web-dev', 'ai', 'fullstack', 'deployment']
  },
  {
    id: 'replit',
    title: 'Replit',
    category: 'Web Developer Toolkit',
    subcategory: 'AI-Powered Development',
    description: 'Cloud-based development platform with AI coding assistance.',
    url: 'https://replit.com',
    featured: false,
    dateAdded: '2023-12-30',
    tags: ['cloud-ide', 'coding', 'deployment']
  },
  {
    id: 'supabase',
    title: 'Supabase',
    category: 'Web Developer Toolkit',
    subcategory: 'Backend & Database Tools',
    description: 'Open-source backend platform with authentication, databases, and storage.',
    url: 'https://supabase.com',
    featured: true,
    dateAdded: '2023-12-29',
    tags: ['backend', 'database', 'auth', 'open-source']
  },
  {
    id: 'neon',
    title: 'Neon',
    category: 'Web Developer Toolkit',
    subcategory: 'Backend & Database Tools',
    description: 'Serverless PostgreSQL database designed for modern web applications.',
    url: 'https://neon.tech',
    featured: false,
    dateAdded: '2023-12-29',
    tags: ['database', 'postgresql', 'serverless']
  },
  {
    id: 'firebase',
    title: 'Firebase',
    category: 'Web Developer Toolkit',
    subcategory: 'Backend & Database Tools',
    description: 'Google\'s backend platform for authentication, databases, and hosting.',
    url: 'https://firebase.google.com',
    featured: false,
    dateAdded: '2023-12-29',
    tags: ['backend', 'google', 'firebase', 'realtime']
  },
  {
    id: 'planetscale',
    title: 'PlanetScale',
    category: 'Web Developer Toolkit',
    subcategory: 'Backend & Database Tools',
    description: 'Highly scalable MySQL platform built for production-grade applications.',
    url: 'https://planetscale.com',
    featured: false,
    dateAdded: '2023-12-29',
    tags: ['database', 'mysql', 'scalable']
  },
  {
    id: 'prisma',
    title: 'Prisma',
    category: 'Web Developer Toolkit',
    subcategory: 'Backend & Database Tools',
    description: 'Modern ORM that makes working with databases easier and safer.',
    url: 'https://prisma.io',
    featured: false,
    dateAdded: '2023-12-29',
    tags: ['orm', 'database', 'development']
  },
  {
    id: 'postman',
    title: 'Postman',
    category: 'Web Developer Toolkit',
    subcategory: 'API & Testing Tools',
    description: 'Industry-standard platform for API testing, development, and collaboration.',
    url: 'https://postman.com',
    featured: true,
    dateAdded: '2023-12-28',
    tags: ['api', 'testing', 'documentation']
  },
  {
    id: 'insomnia',
    title: 'Insomnia',
    category: 'Web Developer Toolkit',
    subcategory: 'API & Testing Tools',
    description: 'Lightweight API client for testing REST and GraphQL endpoints.',
    url: 'https://insomnia.rest',
    featured: false,
    dateAdded: '2023-12-28',
    tags: ['api', 'rest', 'graphql', 'testing']
  },
  {
    id: 'hoppscotch',
    title: 'Hoppscotch',
    category: 'Web Developer Toolkit',
    subcategory: 'API & Testing Tools',
    description: 'Fast, open-source API development ecosystem for developers.',
    url: 'https://hoppscotch.io',
    featured: false,
    dateAdded: '2023-12-28',
    tags: ['api', 'open-source', 'testing']
  },
  {
    id: 'swagger',
    title: 'Swagger Editor',
    category: 'Web Developer Toolkit',
    subcategory: 'API & Testing Tools',
    description: 'Create, document, and test APIs using OpenAPI specifications.',
    url: 'https://swagger.io',
    featured: false,
    dateAdded: '2023-12-28',
    tags: ['api', 'documentation', 'openapi']
  },
  {
    id: 'reqbin',
    title: 'ReqBin',
    category: 'Web Developer Toolkit',
    subcategory: 'API & Testing Tools',
    description: 'Online tool for quickly testing HTTP requests and API endpoints.',
    url: 'https://reqbin.com',
    featured: false,
    dateAdded: '2023-12-28',
    tags: ['api', 'testing', 'http']
  },
  {
    id: 'vercel',
    title: 'Vercel',
    category: 'Web Developer Toolkit',
    subcategory: 'Hosting & Deployment',
    description: 'Deploy modern web applications globally with excellent performance.',
    url: 'https://vercel.com',
    featured: true,
    dateAdded: '2023-12-27',
    tags: ['hosting', 'deployment', 'frontend']
  },
  {
    id: 'netlify',
    title: 'Netlify',
    category: 'Web Developer Toolkit',
    subcategory: 'Hosting & Deployment',
    description: 'Simple hosting platform with continuous deployment and functions.',
    url: 'https://netlify.com',
    featured: false,
    dateAdded: '2023-12-27',
    tags: ['hosting', 'deployment', 'static']
  },
  {
    id: 'cloudflare-pages',
    title: 'Cloudflare Pages',
    category: 'Web Developer Toolkit',
    subcategory: 'Hosting & Deployment',
    description: 'Fast global hosting solution with powerful edge network integration.',
    url: 'https://pages.cloudflare.com',
    featured: false,
    dateAdded: '2023-12-27',
    tags: ['hosting', 'cdn', 'global']
  },
  {
    id: 'render',
    title: 'Render',
    category: 'Web Developer Toolkit',
    subcategory: 'Hosting & Deployment',
    description: 'Deploy web apps, APIs, databases, and background workers.',
    url: 'https://render.com',
    featured: false,
    dateAdded: '2023-12-27',
    tags: ['hosting', 'deployment', 'backend']
  },
  {
    id: 'github-pages',
    title: 'GitHub Pages',
    category: 'Web Developer Toolkit',
    subcategory: 'Hosting & Deployment',
    description: 'Free hosting platform ideal for portfolios and static sites.',
    url: 'https://pages.github.com',
    featured: false,
    dateAdded: '2023-12-27',
    tags: ['hosting', 'free', 'static']
  },
  {
    id: 'caniuse',
    title: 'Can I Use',
    category: 'Web Developer Toolkit',
    subcategory: 'Developer Utilities',
    description: 'Check browser compatibility before using modern web technologies.',
    url: 'https://caniuse.com',
    featured: false,
    dateAdded: '2023-12-26',
    tags: ['browser', 'compatibility', 'reference']
  },
  {
    id: 'roadmapsh-dev',
    title: 'Roadmap.sh',
    category: 'Web Developer Toolkit',
    subcategory: 'Developer Utilities',
    description: 'Interactive learning roadmaps for frontend, backend, and DevOps.',
    url: 'https://roadmap.sh',
    featured: false,
    dateAdded: '2023-12-26',
    tags: ['learning', 'roadmap', 'curriculum']
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    category: 'Web Developer Toolkit',
    subcategory: 'Developer Utilities',
    description: 'Format, validate, and troubleshoot JSON data quickly.',
    url: 'https://jsonformatter.org',
    featured: false,
    dateAdded: '2023-12-26',
    tags: ['json', 'tools', 'utility']
  },
  {
    id: 'tinypng',
    title: 'TinyPNG',
    category: 'Web Developer Toolkit',
    subcategory: 'Developer Utilities',
    description: 'Compress images without quality loss to improve performance.',
    url: 'https://tinypng.com',
    featured: false,
    dateAdded: '2023-12-26',
    tags: ['image', 'optimization', 'performance']
  },
  {
    id: 'squoosh',
    title: 'Squoosh',
    category: 'Web Developer Toolkit',
    subcategory: 'Developer Utilities',
    description: 'Advanced image optimization tool developed by Google.',
    url: 'https://squoosh.app',
    featured: false,
    dateAdded: '2023-12-26',
    tags: ['image', 'optimization', 'google']
  },
  {
    id: 'github-collab',
    title: 'GitHub',
    category: 'Web Developer Toolkit',
    subcategory: 'Version Control & Collaboration',
    description: 'The world\'s most popular platform for version control and collaboration.',
    url: 'https://github.com',
    featured: true,
    dateAdded: '2023-12-25',
    tags: ['git', 'collaboration', 'version-control']
  },
  {
    id: 'gitlab',
    title: 'GitLab',
    category: 'Web Developer Toolkit',
    subcategory: 'Version Control & Collaboration',
    description: 'Complete DevOps platform for source control, CI/CD, and management.',
    url: 'https://gitlab.com',
    featured: false,
    dateAdded: '2023-12-25',
    tags: ['git', 'devops', 'ci-cd']
  },
  {
    id: 'jira',
    title: 'Jira',
    category: 'Web Developer Toolkit',
    subcategory: 'Version Control & Collaboration',
    description: 'Professional project management platform for agile teams.',
    url: 'https://atlassian.com/software/jira',
    featured: false,
    dateAdded: '2023-12-25',
    tags: ['project-management', 'agile', 'tracking']
  },
  {
    id: 'trello',
    title: 'Trello',
    category: 'Web Developer Toolkit',
    subcategory: 'Version Control & Collaboration',
    description: 'Visual task management system using boards, lists, and cards.',
    url: 'https://trello.com',
    featured: false,
    dateAdded: '2023-12-25',
    tags: ['project-management', 'kanban', 'productivity']
  }
];

// Category definitions
